[project]
name = "wrm_pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "boto3",
    "dagster",
    "dagster-aws",
    "dagster-cloud",
    "duckdb",
    "ftfy",
    "hvac",
    "minio",
    "pandas",
    "pandera",
    "python-dotenv",
    "requests",
    "tenacity>=8.0.0"
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "pytest>=9",
    "pytest-cov",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "wrm_pipeline.definitions"
code_location_name = "wrm_pipeline"

[tool.setuptools.packages.find]
include = ["wrm_pipeline*"]
